-- `display_order` drives the user-facing cohort order: higher sorts first, so
-- the newest class leads the filter. It exists because neither existing column
-- carries class order — `created_at` records when the row was written (LGE-1
-- was backfilled after LGE-2 and LGE-3, and LGE-2/LGE-3 share a timestamp),
-- and `name` is a stable lookup slug, not a display key.
--
-- Assigned by identity, so adding a class needs no value: insert order is
-- recency order. `by default` (not `always`) leaves an override for when a
-- class is inserted out of order.
--
-- Cohorts that are not classes are NOT expressed here — pinning 인프런 to the
-- top and toycrane to the bottom lives in `entities/cohort` as a name rule, so
-- no magic number has to be remembered at insert time.
create table public.cohorts (
  id uuid not null default gen_random_uuid() primary key,
  name text not null unique,
  label text not null,
  display_order int not null generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cohorts enable row level security;

create policy "Anyone can view cohorts"
  on public.cohorts for select
  to anon, authenticated
  using (true);

create extension if not exists moddatetime schema extensions;

create trigger handle_updated_at
  before update on public.cohorts
  for each row
  execute procedure extensions.moddatetime (updated_at);
