-- Adds the user-facing cohort ordering key. See `supabase/schemas/cohorts.sql`
-- for why neither `created_at` nor `name` can serve as one.
--
-- Identity fills existing rows as part of the ALTER, so no nullable→backfill→
-- set-not-null dance is needed. The values it assigns follow physical row
-- order, not class order — the companion backfill migration corrects them.
alter table "public"."cohorts"
  add column "display_order" integer generated by default as identity not null;
